name: eslint
description: An example BuildKite plugin for adding your own library of commands to expose to build jobs
author: https://github.com/99designs
original_author: https://github.com/buildkite
requirements:
    - docker
configuration:
    properties:
        assets_path:
            type: string
    additionalProperties: false
